recipseserver:
  version: '@project.version@'
  name: '@project.name@'
  artifact:
    name: '@project.artifactId@'
    group: '@project.groupId@'

logging:
  file:
    name: /application.log
  level:
    org.springframework: INFO
    uk.co.droidinactu.recipeviewer: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'

spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: console
    log-startup-info: true
  application:
    name: recipe-server
  banner:
    #    location: classpath:banner.txt
    mode: CONSOLE
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driverClassName: org.h2.Driver
    password: mypass
    url: jdbc:h2:mem:testdb
    username: sa
  devtools:
    add-properties: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  health:
    defaults:
      enabled: true
    ldap:
      enabled: true
  info:
    defaults:
      enabled: true
    git:
      mode: full