recipseserver:
  version: '@project.version@'
  name: '@project.name@'
  artifact:
    name: '@project.artifactId@'
    group: '@project.groupId@'

server:
  servlet:
    context-path: /recipeserver/v1

logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
  level:
    org.springframework: INFO
    uk.co.droidinactu.recipeviewer: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'
  logback:
    rollingpolicy:
      max-file-size: 10MB

spring:
  application:
    name: recipe-server
  main:
    banner-mode: console
    log-startup-info: true
  banner:
    #    location: classpath:banner.txt
    mode: CONSOLE
  output:
    ansi:
      enabled: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipeServerDb
    username: sa
    password: mypass
    sql-script-encoding: UTF-8
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        batch_versioned_data=true:
        order_updates=true:
        jdbc:
          batch_size=5:
        format_sql: true
    hibernate:
      # create; create-drop; validate; update; none
      ddl-auto: create-drop
      format_sql: true
      default_schema: rs
    show-sql: true
  h2:
    console:
      enabled: true
      path: /dbconsole
      settings:
        trace: true
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  health:
    defaults:
      enabled: true
    ldap:
      enabled: true
  info:
    defaults:
      enabled: true
    git:
      mode: full

